### ISSUE TITLE
About complete point clouds and partial point clouds

### ISSUE THREAD

**Issue by yuluoxingchen111** [tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks#4]
![image](https://github.com/tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks/assets/131221039/74df044b-ecd1-4e22-bf08-ae6e9f6f590c)
![image](https://github.com/tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks/assets/131221039/f9205356-6ad4-4bff-8daa-6b0be05b8e67)
I found that some partial point clouds and complete point clouds do not seem to have a complete inclusion relationship. Can you explain this situation?

**Comment by WeixiaoGao** [comment]
You can consider some of these roof superstructures in partial point clouds as noise, which indeed poses challenges for the application of deep learning frameworks designed for complete point clouds in real-world scenarios. In real data scenarios, these phenomena occur primarily because the rooftop superstructures do not exist in manually created complete point clouds; they might have been added later and captured in subsequent point cloud scans. Alternatively, the structures could be too small to meet the Level of Detail 2 (LoD2) reconstruction standards, such as flagpoles, billboards, and fences, yet these small-scale structures are still detected by aerial LiDAR scanning. We expect the network to learn to ignore these discrepancies or noise and generate predictions that closely resemble manually created real point clouds.
